In [ ]:
import pandas as pd
import numpy as np

# Importing the Datasets

In [ ]:
"""

Import pre-treated Agricultural data from USDA NASS into dataframe: https://quickstats.nass.usda.gov/results/15C3BC70-E0ED-3783-936B-6FE3805765FA
Manually created sub-labels for Agricultural Data to group livestock into: Crop, Cattle, Swine, Poultry, Other Livestock (Sheep, Goat, and Horse), Other Livestock* (all other than previous Other Livestock), Not Specified, amd some blank values for those that we couldn't identify.

"""
county_list = ['ALAMEDA','ALPINE','AMADOR','BUTTE','CALAVERAS','COLUSA','CONTRA COSTA','DEL NORTE','EL DORADO','FRESNO','GLENN','HUMBOLDT','IMPERIAL','INYO','KERN','KINGS','LAKE','LASSEN','LOS ANGELES','MADERA','MARIN','MARIPOSA','MENDOCINO','MERCED','MODOC','MONO','MONTEREY','NAPA','NEVADA','ORANGE','PLACER','PLUMAS','RIVERSIDE','SACRAMENTO','SAN BENITO','SAN BERNARDINO','SAN DIEGO','SAN FRANCISCO','SAN JOAQUIN','SAN LUIS OBISPO','SAN MATEO','SANTA BARBARA','SANTA CLARA','SANTA CRUZ','SHASTA','SIERRA','SISKIYOU','SOLANO','SONOMA','STANISLAUS','SUTTER','TEHAMA','TRINITY','TULARE','TUOLUMNE','VENTURA','YOLO','YUBA']
agriculture_census = pd.read_csv('/Agriculture Census Data (with label).csv')

<ipython-input-2-4916e000356f>:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  agriculture_census = pd.read_csv('/Agriculture Census Data (with label).csv')

In [ ]:
#import GHG inventory sets from California air Resources Board
emissions_2000_2021 = pd.read_csv('/GHG Emissions (2000-2021).csv')
inventory_2000_2021 = emissions_2000_2021
inventory_2000_2021['N2O'] = inventory_2000_2021['GHG'] == 'N2O'
inventory_2000_2021['CO2'] = inventory_2000_2021['GHG'] == 'CO2'
inventory_2000_2021['CH4'] = inventory_2000_2021['GHG'] == 'CH4'

for i in range(2000,2022):
  inventory_2000_2021[str(i)] = inventory_2000_2021[str(i)] * (inventory_2000_2021['N2O'] * 265 + inventory_2000_2021['CO2'] * 1 + inventory_2000_2021['CH4'] * 28)

inventory_2000_2021 = inventory_2000_2021.groupby(['Sublabel']).sum().drop(['Inventory Accountin','Main Sector', 'Sub Sector Level 1', 'Sub Sector Level 2', 'Sub Sector Level 3', 'Main Activity', 'Activity Subset', 'GHG', 'N2O', 'CO2', 'CH4'], axis=1)
inventory_2022 = inventory_2000_2021
inventory_2022['2022'] = inventory_2000_2021['2021']
inventory_2022

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Sublabel,,,,,,,,,,,,,,,,,,,,,
Cattle,22.825593,23.140923,24.588605,25.070238,24.123505,24.839736,25.232453,27.650461,27.644404,26.783747,...,27.226468,27.444354,26.759710,26.419442,26.707242,26.530669,26.230939,26.146760,25.328487,25.328487
Crop Burning - Almond,0.028092,0.029202,0.030021,0.030312,0.031395,0.032505,0.033615,0.035806,0.039112,0.041332,...,0.048487,0.051242,0.052344,0.053446,0.056752,0.060058,0.065017,0.068874,0.068874,0.068874
Crop Burning - Barley,0.000825,0.000954,0.000648,0.000504,0.000653,0.000520,0.000564,0.000383,0.000520,0.000478,...,0.000365,0.000217,0.000252,0.000520,0.000252,0.000226,0.000408,0.000287,0.000287,0.000287
Crop Burning - Corn,0.001702,0.001329,0.001397,0.001161,0.001246,0.001079,0.000914,0.001579,0.001411,0.001329,...,0.001494,0.000788,0.000497,0.000829,0.000664,0.000539,0.000497,0.000497,0.000497,0.000497
Crop Burning - Rice,0.029560,0.014120,0.013717,0.014191,0.014490,0.013568,0.014117,0.012988,0.012616,0.011228,...,0.009548,0.007757,0.006654,0.005780,0.006727,0.004024,0.005191,0.005818,0.005818,0.005818
Crop Burning - Walnut,0.011117,0.011327,0.011667,0.011824,0.011876,0.011928,0.011980,0.012370,0.012765,0.013314,...,0.015538,0.016114,0.016663,0.017500,0.018599,0.019436,0.020273,0.021110,0.021110,0.021110
Crop Burning - Wheat,0.006145,0.005818,0.005180,0.006625,0.005300,0.004656,0.003975,0.004470,0.006878,0.006183,...,0.004973,0.002774,0.002967,0.002739,0.002299,0.001857,0.001541,0.001285,0.001285,0.001285
Crop Fertilizer,3.524914,3.400165,3.529205,3.441326,3.388313,3.354292,3.470434,3.127841,2.998934,2.911248,...,2.746059,2.549484,2.349996,2.376818,2.415292,2.499868,2.451852,2.587027,2.587027,2.587027
Drained Histosols,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,...,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566,0.132566
Fuel Combustion,3.672629,3.796353,4.222812,4.352711,4.594384,4.598195,5.099683,3.708040,4.021096,2.547464,...,3.252544,3.397848,3.193445,2.826695,2.245389,2.690346,2.191784,2.351064,2.411551,2.411551
Other Livestock,0.666317,0.683689,0.699951,0.757084,0.802347,0.883670,0.884466,0.864197,0.858557,0.892789,...,0.890428,0.891081,0.895669,0.889417,0.896144,0.887550,0.883078,0.887792,0.882541,0.882541
Poultry,0.347857,0.347360,0.335779,0.316421,0.286501,0.280002,0.282289,0.297021,0.286913,0.278126,...,0.236357,0.203841,0.209141,0.209141,0.209141,0.209141,0.209141,0.209141,0.209141,0.209141
Rice Emissions,0.789400,0.813708,0.853556,0.904703,0.879412,0.959505,0.797280,1.047696,0.799544,0.891801,...,0.966874,0.870775,0.751875,1.001028,0.724521,0.834691,0.896625,0.859947,0.859947,0.859947
Swine,0.078690,0.059716,0.084251,0.079308,0.081485,0.080633,0.077429,0.086200,0.045791,0.061072,...,0.054998,0.061542,0.053146,0.052655,0.053146,0.053638,0.054048,0.053476,0.052762,0.052762

# Livestock

In [ ]:
"""

This code is for Livestock only in the agriculture dataset

"""
livestock = agriculture_census[(agriculture_census['Sublabel'] == 'Other Livestock') | (agriculture_census['Sublabel'] == 'Cattle') | (agriculture_census['Sublabel'] == 'Swine') | (agriculture_census['Sublabel'] == 'Poultry')]
livestock = livestock[livestock['Domain'] == 'TOTAL']
livestock = livestock[livestock['Data Item'].str.contains('MEASURED IN HEAD')]
livestock_cleaned = livestock[['County', 'State', 'Year', 'Data Item', 'Value', 'Sublabel']]
livestock_cleaned = livestock_cleaned[~livestock_cleaned['Value'].str.contains('D')]
livestock_cleaned['Value'] = livestock_cleaned['Value'].str.replace(',', '').astype(int)
livestock_dict = {'Cattle': ['CATTLE, INCL CALVES'], 'Swine': ['HOGS - SALES'], 'Poultry': ['POULTRY TOTALS - HATCHED'], 'Other Livestock': ['EQUINE, HORSES & PONIES - SALES', 'GOATS - SALES', 'SHEEP, INCL LAMBS - SALES']}

#Creating subtable for cattle only (exclude Bison)
def livestock_emissions(livestock_type):
  animal = livestock_cleaned[livestock_cleaned['Sublabel'] == livestock_type].sort_values(by = 'Value', ascending = False)
  animal = animal[animal['Data Item'].str.contains('|'.join(livestock_dict[livestock_type]))]
  animal.drop('Sublabel', axis = 1, inplace = True)
  animal.columns = [x.lower() for x in animal.columns]
  animal = animal.groupby(['county', 'year'],as_index=False).agg(sum)
  animal = animal.pivot(columns = 'year', index = 'county', values = 'value').fillna(0)
  animal_proportions = animal.div(animal.sum(axis=0), axis=1)
  combined_df = pd.DataFrame()
  for col in animal_proportions.columns:
    if (col != 1997):
      combined_df[col] = animal_proportions[col] * inventory_2000_2021.loc[livestock_type, str(col)]
  for county in county_list:
    if county not in combined_df.index:
      combined_df.loc[county] = [0, 0, 0, 0, 0]
  return combined_df.sort_index()

#example code here below will create a county-level table for 2002 - 2022 for other livestock (horse, sheep, and goats)
livestock_emissions('Other Livestock')

#For NaN values in the pivot, we replaced the NaN values with 0

<ipython-input-4-a7ca944fb8cb>:20: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  animal = animal.groupby(['county', 'year'],as_index=False).agg(sum)

                     2002      2007      2012      2017      2022
county
ALAMEDA          0.001212  0.002452  0.001579  0.001433  0.001230
ALPINE           0.000000  0.000000  0.000000  0.000000  0.000000
AMADOR           0.002429  0.003194  0.006882  0.001451  0.003581
BUTTE            0.003109  0.007528  0.004480  0.004804  0.008047
CALAVERAS        0.002368  0.003086  0.003812  0.006199  0.007641
COLUSA           0.006178  0.008009  0.001773  0.000680  0.010267
CONTRA COSTA     0.002098  0.003428  0.000824  0.006434  0.001794
DEL NORTE        0.000030  0.000289  0.000149  0.000357  0.000155
EL DORADO        0.002687  0.003673  0.002579  0.004411  0.005121
FRESNO           0.028419  0.054087  0.063096  0.053332  0.063391
GLENN            0.006449  0.005851  0.003199  0.004931  0.006912
HUMBOLDT         0.004934  0.004943  0.007184  0.008281  0.012950
IMPERIAL         0.137934  0.180364  0.139544  0.000073  0.000000
INYO             0.000122  0.000208  0.000103  0.000379  0.000173
KERN             0.118900  0.152958  0.101847  0.156532  0.148353
KINGS            0.000784  0.001723  0.015895  0.006142  0.004758
LAKE             0.002176  0.001777  0.002553  0.000539  0.001745
LASSEN           0.006131  0.011605  0.010026  0.014377  0.012844
LOS ANGELES      0.003545  0.006706  0.001178  0.003548  0.004691
MADERA           0.011989  0.008594  0.002071  0.004067  0.011984
MARIN            0.007492  0.010259  0.006660  0.016763  0.004015
MARIPOSA         0.000912  0.001300  0.001100  0.001755  0.003542
MENDOCINO        0.008427  0.007249  0.010369  0.009589  0.009104
MERCED           0.009606  0.026258  0.023425  0.045427  0.025194
MODOC            0.005997  0.006588  0.020072  0.015688  0.007014
MONO             0.000040  0.000144  0.000096  0.000162  0.000176
MONTEREY         0.003067  0.011711  0.006864  0.005535  0.001734
NAPA             0.001595  0.000978  0.001645  0.002581  0.003394
NEVADA           0.003425  0.003901  0.003537  0.003854  0.008709
ORANGE           0.000535  0.000365  0.000000  0.000038  0.000257
PLACER           0.006266  0.007067  0.008921  0.008568  0.017331
PLUMAS           0.000154  0.000100  0.000215  0.000707  0.001276
RIVERSIDE        0.038128  0.049463  0.093292  0.036596  0.021486
SACRAMENTO       0.005253  0.009163  0.009202  0.014139  0.024842
SAN BENITO       0.005176  0.002416  0.001837  0.002865  0.008353
SAN BERNARDINO   0.015437  0.005576  0.001601  0.003835  0.001540
SAN DIEGO        0.004423  0.006374  0.004187  0.005847  0.008449
SAN FRANCISCO    0.000000  0.000000  0.000000  0.000000  0.000000
SAN JOAQUIN      0.018302  0.023122  0.026405  0.026912  0.049201
SAN LUIS OBISPO  0.015928  0.018183  0.015771  0.030170  0.040981
SAN MATEO        0.000172  0.000423  0.000169  0.000306  0.001935
SANTA BARBARA    0.008463  0.006083  0.002881  0.001790  0.006217
SANTA CLARA      0.001836  0.005845  0.002755  0.010133  0.003073
SANTA CRUZ       0.000221  0.000403  0.004679  0.000154  0.000610
SHASTA           0.002589  0.004590  0.003439  0.006348  0.006521
SIERRA           0.000037  0.000000  0.000000  0.000823  0.000000
SISKIYOU         0.005349  0.004386  0.002343  0.008100  0.006887
SOLANO           0.071023  0.049461  0.064105  0.155156  0.205639
SONOMA           0.028834  0.029865  0.030986  0.035145  0.022604
STANISLAUS       0.010127  0.009141  0.023189  0.032410  0.014719
SUTTER           0.008338  0.009535  0.008864  0.007512  0.009985
TEHAMA           0.009209  0.010956  0.013492  0.010415  0.013020
TRINITY          0.000000  0.000214  0.000448  0.000628  0.000197
TULARE           0.043917  0.063082  0.103353  0.002183  0.012886
TUOLUMNE         0.002466  0.002865  0.001332  0.001693  0.002474
VENTURA          0.001017  0.002110  0.001283  0.003864  0.001368
YOLO             0.012529  0.010844  0.020313  0.106385  0.026664
YUBA             0.002167  0.003701  0.005542  0.004100  0.005506

# Crops

In [ ]:
#create new dataframe to filter needed columns
agriculture_cleaned2 = agriculture_census[['County', 'State', 'Year', 'Data Item', 'Value']]
#filter for only agriculture yield rows
agriculture_cleaned2 = agriculture_cleaned2[agriculture_cleaned2['Data Item'].str.contains(' - PRODUCTION, ')]
#split data item column to open units of measurement
units = agriculture_cleaned2['Data Item'].str.split(' - PRODUCTION, MEASURED IN')
# #Add new column called units containing the units, reassign data units to simply names of agricultural item, and rename columns
agriculture_cleaned2['units'] = units.apply(lambda x: x[1])
agriculture_cleaned2['Data Item'] = units.apply(lambda x: x[0])
agriculture_cleaned2.rename(columns={'Data Item':'crop_or_livestock','Value':'yield','County':'county','State':'state','Year':'year'}, inplace=True)
#Filter out the non integer values in yield
agriculture_cleaned2 = agriculture_cleaned2[agriculture_cleaned2['yield'] != ' (D)']
#Convert yield values into int
agriculture_cleaned2['yield'] = agriculture_cleaned2['yield'].str.replace(",", "").astype(int)
agriculture_cleaned2

<ipython-input-5-5db1a07b6131>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agriculture_cleaned2['units'] = units.apply(lambda x: x[1])
<ipython-input-5-5db1a07b6131>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agriculture_cleaned2['Data Item'] = units.apply(lambda x: x[0])
<ipython-input-5-5db1a07b6131>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agriculture_cleaned2.rename(columns={'Data Item':'crop_or_livestock','Value':'yield','County':'county','State':'state','Year':'year'}, inplace=True)

,county,state,year,crop_or_livestock,yield,units
215,ALAMEDA,CALIFORNIA,2022,HAY,3746,TONS
235,ALAMEDA,CALIFORNIA,2022,HAY & HAYLAGE,4018,"TONS, DRY BASIS"
246,ALAMEDA,CALIFORNIA,2022,"HEMP, INDUSTRIAL, IN THE OPEN, FLORAL",5531832,LB
255,ALAMEDA,CALIFORNIA,2022,HONEY,2411954,LB
527,ALAMEDA,CALIFORNIA,2022,WOOL,909,LB
...,...,...,...,...,...,...
187412,SANTA BARBARA,CALIFORNIA,1997,OATS,8272,BU
187473,VENTURA,CALIFORNIA,1997,"BEANS, DRY EDIBLE, LIMA",22227,CWT
187539,VENTURA,CALIFORNIA,1997,"HAY, ALFALFA",22156,TONS
187544,VENTURA,CALIFORNIA,1997,"HAY, SMALL GRAIN",10485,TONS
187623,VENTURA,CALIFORNIA,1997,WOOL,1835,LB

In [ ]:
#create new dataframe to filter needed columns
agriculture_cleaned2 = agriculture_census[['County', 'State', 'Year', 'Commodity','Data Item', 'Value']].copy()
#filter for only agriculture yield rows measured in acres
agriculture_cleaned2 = agriculture_cleaned2[agriculture_cleaned2['Data Item'].str.contains(' - ACRES')]
#split data item column to open units of measurement
units = agriculture_cleaned2['Data Item'].str.split(' - ACRES')
# #Add new column called units containing the units, reassign data units to simply names of agricultural item, and rename columns
agriculture_cleaned2['units'] = units.apply(lambda x: x[1])
agriculture_cleaned2['Data Item'] = units.apply(lambda x: x[0])
agriculture_cleaned2.rename(columns={'Data Item':'crop_or_livestock','Value':'yield','County':'county','State':'state','Year':'year'}, inplace=True)
#Filter out the non integer values in yield
agriculture_cleaned2 = agriculture_cleaned2[agriculture_cleaned2['yield'] != ' (D)']
agriculture_cleaned2 = agriculture_cleaned2[agriculture_cleaned2['yield'] != ' (Z)']
#Filter out all subcategories by taking the max of each commodity for each county for each year
agriculture_cleaned2 = agriculture_cleaned2.groupby(['county','year','Commodity'], as_index=False)['yield'].max()
#Convert yield values into int
agriculture_cleaned2['yield'] = agriculture_cleaned2['yield'].str.replace(',', '').astype(int)
agriculture_cleaned2

        county  year             Commodity  yield
0      ALAMEDA  1997                BARLEY    245
1      ALAMEDA  1997  BEDDING PLANT TOTALS      6
2      ALAMEDA  1997                  CORN    496
3      ALAMEDA  1997   FLORICULTURE TOTALS    115
4      ALAMEDA  1997                   HAY    815
...        ...   ...                   ...    ...
14743     YUBA  2022            TANGERINES     35
14744     YUBA  2022              TOMATOES     92
14745     YUBA  2022       TREE NUT TOTALS  23833
14746     YUBA  2022      VEGETABLE TOTALS   1219
14747     YUBA  2022               WALNUTS  22558

[14748 rows x 4 columns]

In [ ]:
nitrogen_application = pd.read_csv('/Nitrogen Application.csv')

In [ ]:
nitrogen_application

                   Commodity  Fertilizer Needed (lbs/acre)
0                    ALMONDS                         225.0
1                 PISTACHIOS                         225.0
2                  ASPARAGUS                         225.0
3                    RHUBARB                         225.0
4                     CELERY                         225.0
..                       ...                           ...
160      FLORICULTURE TOTALS                           0.0
161  FRUIT & TREE NUT TOTALS                           0.0
162      HORTICULTURE TOTALS                           0.0
163        NON-CITRUS TOTALS                           0.0
164         VEGETABLE TOTALS                           0.0

[165 rows x 2 columns]

In [ ]:
# Fertilizer
crops_fertilizer = agriculture_cleaned2.merge(nitrogen_application, on='Commodity')
crops_fertilizer['Fertilizer (lbs)'] = crops_fertilizer['Fertilizer Needed (lbs/acre)'] * crops_fertilizer['yield']
crops_fertilizer = crops_fertilizer.groupby(['county', 'year'], as_index=False)['Fertilizer (lbs)'].sum()
crops_fertilizer = crops_fertilizer.pivot(columns = 'year', index = 'county', values = 'Fertilizer (lbs)').fillna(0)
crops_proportions = crops_fertilizer.div(crops_fertilizer.sum(axis=0), axis=1)
combined_df = pd.DataFrame()
for col in crops_proportions.columns:
    if (col != 1997):
      combined_df[col] = crops_proportions[col] * inventory_2000_2021.loc['Crop Fertilizer', str(col)]
for county in county_list:
  if county not in combined_df.index:
    combined_df.loc[county] = [0, 0, 0, 0, 0]
combined_df

                     2002      2007      2012      2017      2022
county
ALAMEDA          0.002265  0.004732  0.003714  0.002396  0.002371
ALPINE           0.000526  0.000287  0.000133  0.000000  0.000000
AMADOR           0.002083  0.002424  0.003563  0.002063  0.001488
BUTTE            0.113308  0.094926  0.092927  0.071418  0.070320
CALAVERAS        0.001374  0.001522  0.001762  0.001286  0.000871
COLUSA           0.122156  0.109763  0.090980  0.083738  0.086530
CONTRA COSTA     0.011421  0.008071  0.011784  0.005714  0.002593
DEL NORTE        0.001083  0.001009  0.001753  0.001026  0.001583
EL DORADO        0.002287  0.002143  0.001634  0.001355  0.001155
FRESNO           0.434275  0.324676  0.372915  0.309473  0.248521
GLENN            0.085283  0.075894  0.108659  0.083613  0.089972
HUMBOLDT         0.002877  0.002276  0.001810  0.002252  0.001798
IMPERIAL         0.150776  0.139658  0.154003  0.117314  0.209778
INYO             0.001905  0.001121  0.001718  0.000612  0.002485
KERN             0.352286  0.356070  0.360508  0.229932  0.246895
KINGS            0.163609  0.109654  0.132415  0.102984  0.141416
LAKE             0.009213  0.007814  0.008138  0.005082  0.003538
LASSEN           0.014517  0.014350  0.012593  0.014037  0.021473
LOS ANGELES      0.005070  0.009111  0.012657  0.002360  0.004700
MADERA           0.158736  0.172164  0.151373  0.085535  0.101464
MARIN            0.001201  0.000472  0.003759  0.003168  0.002669
MARIPOSA         0.000320  0.000048  0.000350  0.000206  0.000510
MENDOCINO        0.012109  0.010416  0.012990  0.009453  0.006796
MERCED           0.234968  0.251091  0.206721  0.153751  0.153640
MODOC            0.058047  0.052064  0.057388  0.041083  0.038213
MONO             0.006352  0.004516  0.005848  0.003037  0.006411
MONTEREY         0.090262  0.085850  0.090978  0.086237  0.072039
NAPA             0.016866  0.015374  0.014949  0.016769  0.011873
NEVADA           0.001171  0.001240  0.000570  0.000473  0.000323
ORANGE           0.002786  0.001858  0.002094  0.000719  0.000720
PLACER           0.011147  0.006760  0.007549  0.003237  0.004397
PLUMAS           0.005618  0.004281  0.003519  0.004314  0.003478
RIVERSIDE        0.081811  0.066422  0.051337  0.042927  0.056857
SACRAMENTO       0.038795  0.034405  0.025586  0.024233  0.028419
SAN BENITO       0.013137  0.013499  0.005616  0.005392  0.007565
SAN BERNARDINO   0.013591  0.012616  0.010693  0.007695  0.004284
SAN DIEGO        0.029159  0.027367  0.017352  0.013377  0.008826
SAN JOAQUIN      0.228103  0.177395  0.201109  0.174951  0.183276
SAN LUIS OBISPO  0.032045  0.038211  0.034344  0.020638  0.023501
SAN MATEO        0.001846  0.001033  0.000660  0.000799  0.000398
SANTA BARBARA    0.045594  0.037595  0.030839  0.032171  0.034246
SANTA CLARA      0.008492  0.006431  0.008030  0.004941  0.004856
SANTA CRUZ       0.010942  0.006843  0.008795  0.005262  0.003200
SHASTA           0.008431  0.006287  0.007546  0.007800  0.007364
SIERRA           0.001132  0.000918  0.001002  0.000956  0.001112
SISKIYOU         0.038885  0.028875  0.061007  0.030348  0.037339
SOLANO           0.036902  0.039217  0.035984  0.038921  0.043887
SONOMA           0.025601  0.032610  0.027225  0.007928  0.020429
STANISLAUS       0.200595  0.137170  0.138382  0.114082  0.124149
SUTTER           0.095357  0.098552  0.098866  0.050864  0.042380
TEHAMA           0.036246  0.024981  0.031040  0.022343  0.023433
TRINITY          0.000389  0.000477  0.000252  0.000231  0.000264
TULARE           0.294319  0.292406  0.255694  0.234484  0.270800
TUOLUMNE         0.000297  0.000217  0.000179  0.000230  0.000181
VENTURA          0.060337  0.049184  0.040713  0.038441  0.030321
YOLO             0.113275  0.096835  0.076955  0.062450  0.059940
YUBA             0.038027  0.026666  0.025442  0.029188  0.029980
SAN FRANCISCO    0.000000  0.000000  0.000000  0.000000  0.000000

In [ ]:
# Rice
rice_production = agriculture_cleaned2[(agriculture_cleaned2['Commodity'] == 'RICE') | (agriculture_cleaned2['Commodity'] == 'WILD RICE')]
rice_production = rice_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
rice_production = rice_production.pivot(columns = 'year', index = 'county', values = 'yield').fillna(0)
rice_production = rice_production.div(rice_production.sum(axis=0), axis=1)
rice_emissions = pd.DataFrame()
for col in rice_production.columns:
    if (col != 1997):
      rice_emissions[col] = rice_production[col] * inventory_2000_2021.loc['Rice Emissions', str(col)]
for county in county_list:
  if county not in rice_emissions.index:
    rice_emissions.loc[county] = [0, 0, 0, 0, 0]
rice_emissions

<ipython-input-10-4c8cbdaef4f2>:3: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  rice_production = rice_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)

                     2002      2007      2012      2017      2022
county
BUTTE            0.149252  0.188606  0.153938  0.121028  0.212832
COLUSA           0.221587  0.281907  0.249477  0.204690  0.113028
FRESNO           0.009487  0.009604  0.007213  0.003624  0.000000
GLENN            0.132320  0.178921  0.153587  0.133471  0.107659
LASSEN           0.000000  0.000000  0.000712  0.000000  0.006437
MERCED           0.003978  0.005641  0.005637  0.002711  0.000891
MODOC            0.007451  0.007478  0.007649  0.000000  0.000000
PLACER           0.018945  0.017761  0.015261  0.009496  0.009843
SACRAMENTO       0.011270  0.009753  0.003321  0.005177  0.010440
SAN JOAQUIN      0.009873  0.008245  0.006856  0.004398  0.026218
SHASTA           0.002834  0.009721  0.008397  0.014635  0.050942
STANISLAUS       0.001934  0.000709  0.000357  0.000000  0.000000
SUTTER           0.175102  0.196499  0.197496  0.142655  0.144394
TEHAMA           0.001429  0.001745  0.002525  0.001468  0.000000
YOLO             0.054426  0.064686  0.059170  0.041136  0.032374
YUBA             0.053669  0.066420  0.055852  0.040034  0.144890
ALAMEDA          0.000000  0.000000  0.000000  0.000000  0.000000
ALPINE           0.000000  0.000000  0.000000  0.000000  0.000000
AMADOR           0.000000  0.000000  0.000000  0.000000  0.000000
CALAVERAS        0.000000  0.000000  0.000000  0.000000  0.000000
CONTRA COSTA     0.000000  0.000000  0.000000  0.000000  0.000000
DEL NORTE        0.000000  0.000000  0.000000  0.000000  0.000000
EL DORADO        0.000000  0.000000  0.000000  0.000000  0.000000
HUMBOLDT         0.000000  0.000000  0.000000  0.000000  0.000000
IMPERIAL         0.000000  0.000000  0.000000  0.000000  0.000000
INYO             0.000000  0.000000  0.000000  0.000000  0.000000
KERN             0.000000  0.000000  0.000000  0.000000  0.000000
KINGS            0.000000  0.000000  0.000000  0.000000  0.000000
LAKE             0.000000  0.000000  0.000000  0.000000  0.000000
LOS ANGELES      0.000000  0.000000  0.000000  0.000000  0.000000
MADERA           0.000000  0.000000  0.000000  0.000000  0.000000
MARIN            0.000000  0.000000  0.000000  0.000000  0.000000
MARIPOSA         0.000000  0.000000  0.000000  0.000000  0.000000
MENDOCINO        0.000000  0.000000  0.000000  0.000000  0.000000
MONO             0.000000  0.000000  0.000000  0.000000  0.000000
MONTEREY         0.000000  0.000000  0.000000  0.000000  0.000000
NAPA             0.000000  0.000000  0.000000  0.000000  0.000000
NEVADA           0.000000  0.000000  0.000000  0.000000  0.000000
ORANGE           0.000000  0.000000  0.000000  0.000000  0.000000
PLUMAS           0.000000  0.000000  0.000000  0.000000  0.000000
RIVERSIDE        0.000000  0.000000  0.000000  0.000000  0.000000
SAN BENITO       0.000000  0.000000  0.000000  0.000000  0.000000
SAN BERNARDINO   0.000000  0.000000  0.000000  0.000000  0.000000
SAN DIEGO        0.000000  0.000000  0.000000  0.000000  0.000000
SAN FRANCISCO    0.000000  0.000000  0.000000  0.000000  0.000000
SAN LUIS OBISPO  0.000000  0.000000  0.000000  0.000000  0.000000
SAN MATEO        0.000000  0.000000  0.000000  0.000000  0.000000
SANTA BARBARA    0.000000  0.000000  0.000000  0.000000  0.000000
SANTA CLARA      0.000000  0.000000  0.000000  0.000000  0.000000
SANTA CRUZ       0.000000  0.000000  0.000000  0.000000  0.000000
SIERRA           0.000000  0.000000  0.000000  0.000000  0.000000
SISKIYOU         0.000000  0.000000  0.000000  0.000000  0.000000
SOLANO           0.000000  0.000000  0.000000  0.000000  0.000000
SONOMA           0.000000  0.000000  0.000000  0.000000  0.000000
TRINITY          0.000000  0.000000  0.000000  0.000000  0.000000
TULARE           0.000000  0.000000  0.000000  0.000000  0.000000
TUOLUMNE         0.000000  0.000000  0.000000  0.000000  0.000000
VENTURA          0.000000  0.000000  0.000000  0.000000  0.000000

In [ ]:
# Burning - Rice
rice_burning = pd.DataFrame()
for col in rice_production.columns:
    if (col != 1997):
      rice_burning[col] = rice_production[col] * inventory_2000_2021.loc['Crop Burning - Rice', str(col)]
for county in county_list:
  if county not in rice_burning.index:
    rice_burning.loc[county] = [0, 0, 0, 0, 0]

# Burning - Barley
barley_production = agriculture_cleaned2[(agriculture_cleaned2['Commodity'] == 'BARLEY')]
barley_production = barley_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
barley_production = barley_production.pivot(columns = 'year', index = 'county', values = 'yield').fillna(0)
barley_production = barley_production.div(barley_production.sum(axis=0), axis=1)
barley_burning = pd.DataFrame()
for col in barley_production.columns:
    if (col != 1997):
      barley_burning[col] = barley_production[col] * inventory_2000_2021.loc['Crop Burning - Barley', str(col)]
for county in county_list:
  if county not in barley_burning.index:
    barley_burning.loc[county] = [0, 0, 0, 0, 0]

# Burning - Wheat
wheat_production = agriculture_cleaned2[(agriculture_cleaned2['Commodity'] == 'WHEAT')]
wheat_production = wheat_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
wheat_production = wheat_production.pivot(columns = 'year', index = 'county', values = 'yield').fillna(0)
wheat_production = wheat_production.div(wheat_production.sum(axis=0), axis=1)
wheat_burning = pd.DataFrame()
for col in wheat_production.columns:
    if (col != 1997):
      wheat_burning[col] = wheat_production[col] * inventory_2000_2021.loc['Crop Burning - Wheat', str(col)]
for county in county_list:
  if county not in wheat_burning.index:
    wheat_burning.loc[county] = [0, 0, 0, 0, 0]

# Burning - Almonds
almond_production = agriculture_cleaned2[(agriculture_cleaned2['Commodity'] == 'ALMONDS')]
almond_production = almond_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
almond_production = almond_production.pivot(columns = 'year', index = 'county', values = 'yield').fillna(0)
almond_production = almond_production.div(almond_production.sum(axis=0), axis=1)
almond_burning = pd.DataFrame()
for col in almond_production.columns:
    if (col != 1997):
      almond_burning[col] = almond_production[col] * inventory_2000_2021.loc['Crop Burning - Almond', str(col)]
for county in county_list:
  if county not in almond_burning.index:
    almond_burning.loc[county] = [0, 0, 0, 0, 0]

# Burning - Walnuts
walnut_production = agriculture_cleaned2[(agriculture_cleaned2['Commodity'] == 'WALNUTS')]
walnut_production = walnut_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
walnut_production = walnut_production.pivot(columns = 'year', index = 'county', values = 'yield').fillna(0)
walnut_production = walnut_production.div(walnut_production.sum(axis=0), axis=1)
walnut_burning = pd.DataFrame()
for col in walnut_production.columns:
    if (col != 1997):
      walnut_burning[col] = walnut_production[col] * inventory_2000_2021.loc['Crop Burning - Walnut', str(col)]
for county in county_list:
  if county not in walnut_burning.index:
    walnut_burning.loc[county] = [0, 0, 0, 0, 0]

total_burning = almond_burning + walnut_burning + wheat_burning + barley_burning + rice_burning
total_burning

<ipython-input-11-a982591824cd>:12: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  barley_production = barley_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
<ipython-input-11-a982591824cd>:25: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  wheat_production = wheat_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
<ipython-input-11-a982591824cd>:38: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  almond_production = almond_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)
<ipython-input-11-a982591824cd>:51: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  walnut_production = walnut_production.groupby(['county', 'year'], as_index=False)['yield'].agg(sum)

,2002,2007,2012,2017,2022
county,,,,,
ALAMEDA,4.071157e-06,4.612536e-06,0.000000e+00,0.000000e+00,0.000000e+00
ALPINE,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
AMADOR,8.207216e-05,4.099360e-05,0.000000e+00,4.636016e-07,1.174538e-05
BUTTE,6.155113e-03,7.272179e-03,6.864214e-03,3.260186e-03,5.197964e-03
CALAVERAS,8.572260e-05,8.479942e-05,1.243360e-04,8.295912e-05,2.990901e-05
COLUSA,6.515447e-03,7.271827e-03,2.768376e-03,4.115348e-03,9.833789e-03
CONTRA COSTA,1.527699e-04,1.079510e-04,1.754492e-04,1.486277e-04,3.226799e-05
DEL NORTE,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
EL DORADO,9.709163e-06,5.385259e-06,6.853201e-06,1.097305e-06,1.307887e-05
FRESNO,6.569878e-03,3.672428e-03,4.732195e-03,8.508771e-03,4.331027e-03
GLENN,3.855127e-03,3.266095e-03,7.714542e-03,3.549772e-03,1.146685e-02
HUMBOLDT,5.035102e-07,1.084487e-07,9.325200e-07,4.696870e-07,5.682475e-07
IMPERIAL,1.255271e-03,7.825316e-04,1.474101e-03,4.352030e-04,5.162935e-04
INYO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
KERN,4.920093e-04,3.668783e-03,1.673966e-02,6.169454e-03,4.542895e-03
KINGS,2.939606e-03,1.084458e-03,3.076476e-03,1.670900e-03,6.872347e-03
LAKE,1.038656e-04,5.294464e-04,1.464544e-04,3.659901e-04,6.533242e-07
LASSEN,1.066923e-05,9.590568e-06,2.284985e-05,1.504319e-05,5.795386e-05
LOS ANGELES,1.762106e-05,1.458803e-06,7.960272e-05,0.000000e+00,8.603472e-05
MADERA,3.452127e-03,7.406680e-03,1.013189e-02,3.604561e-03,1.757945e-03
MARIN,1.510530e-06,4.337947e-07,5.801585e-06,6.559531e-08,0.000000e+00
MARIPOSA,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
MENDOCINO,4.279836e-06,9.977277e-06,9.636039e-06,8.344829e-07,2.952391e-06
MERCED,6.386315e-03,9.433316e-03,2.502011e-03,5.089704e-03,3.303543e-03
MODOC,3.308961e-04,2.048602e-04,2.629382e-04,2.223194e-04,3.599493e-05
MONO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
MONTEREY,1.564079e-04,7.069372e-05,1.444744e-04,2.402817e-05,1.367184e-05
NAPA,3.436457e-05,3.859286e-05,1.865040e-05,6.304982e-06,2.481841e-06
NEVADA,2.643428e-06,1.062182e-06,2.606690e-07,2.730481e-07,1.140212e-07
ORANGE,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
PLACER,3.132989e-04,2.471245e-04,2.158553e-04,8.960564e-05,2.584546e-04
PLUMAS,7.552652e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
RIVERSIDE,1.479472e-04,1.730485e-04,1.021329e-04,1.437103e-04,7.566338e-05
SACRAMENTO,4.871436e-04,2.859105e-04,1.557353e-04,3.283416e-04,6.343792e-04
SAN BENITO,3.698182e-04,0.000000e+00,2.417240e-04,1.765395e-04,0.000000e+00
SAN BERNARDINO,1.118151e-05,7.705779e-06,3.218134e-06,2.849179e-05,1.231429e-05
SAN DIEGO,1.498058e-05,5.355520e-06,1.623238e-05,5.409834e-07,0.000000e+00
SAN FRANCISCO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
SAN JOAQUIN,3.515984e-03,1.243691e-03,2.760828e-03,1.855476e-02,1.574112e-02
SAN LUIS OBISPO,2.178627e-04,5.325299e-04,6.946179e-04,2.417310e-04,5.753780e-05
SAN MATEO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
SANTA BARBARA,1.137237e-04,1.520190e-04,5.255662e-05,2.232427e-05,1.393022e-04
SANTA CLARA,1.028893e-05,6.665776e-05,1.197225e-05,9.627575e-06,3.677653e-05
SANTA CRUZ,2.265796e-06,0.000000e+00,1.523657e-06,0.000000e+00,0.000000e+00
SHASTA,1.202711e-04,1.251719e-04,1.160031e-04,2.096315e-04,3.934766e-04
SIERRA,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
SISKIYOU,3.442425e-04,1.891404e-04,4.230232e-04,1.616868e-04,1.532662e-05
SOLANO,4.068807e-04,1.412946e-03,1.723215e-03,1.209336e-03,1.546136e-03
SONOMA,5.916244e-06,4.337947e-06,2.007816e-06,1.621213e-05,7.792428e-06
STANISLAUS,6.137653e-03,2.542469e-03,2.564698e-03,4.495683e-03,6.712472e-03
SUTTER,3.917348e-03,4.040872e-03,4.191480e-03,3.477157e-03,4.034553e-03
TEHAMA,1.115453e-03,1.132167e-03,1.148619e-03,1.853967e-03,2.263730e-03
TRINITY,1.007020e-06,2.168973e-07,0.000000e+00,0.000000e+00,0.000000e+00
TULARE,1.533255e-03,3.675067e-03,1.932890e-03,1.234755e-02,1.042471e-02
TUOLUMNE,0.000000e+00,0.000000e+00,8.507539e-08,1.177548e-05,0.000000e+00
VENTURA,5.790367e-06,1.214625e-05,1.119024e-05,2.021303e-05,3.530033e-06
YOLO,1.734815e-03,3.339242e-03,1.416699e-03,1.419001e-03,4.478564e-03
YUBA,2.087013e-03,1.861174e-03,1.242557e-03,2.537920e-03,2.428068e-03

In [ ]:
agriculture_cleaned2[~agriculture_cleaned2['Commodity'].str.contains('TOTAL')].groupby(['county', 'year'], as_index = False)['yield'].agg(sum).pivot(columns = 'year', index = 'county', values = 'yield').fillna(0)

<ipython-input-12-311ed5ea7ad1>:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  agriculture_cleaned2[~agriculture_cleaned2['Commodity'].str.contains('TOTAL')].groupby(['county', 'year'], as_index = False)['yield'].agg(sum).pivot(columns = 'year', index = 'county', values = 'yield').fillna(0)

year,1997,2002,2007,2012,2017,2022
county,,,,,,
ALAMEDA,4230.0,7527.0,19998.0,16033.0,10846.0,13782.0
ALPINE,0.0,1700.0,1027.0,480.0,0.0,0.0
AMADOR,4716.0,7002.0,8680.0,12773.0,13202.0,7695.0
BUTTE,220556.0,301078.0,274546.0,271812.0,209352.0,245462.0
CALAVERAS,573.0,4867.0,5115.0,5617.0,6034.0,5167.0
COLUSA,267544.0,327301.0,313064.0,275361.0,273646.0,259987.0
CONTRA COSTA,18958.0,34862.0,27462.0,39602.0,25736.0,12674.0
DEL NORTE,2975.0,5400.0,5977.0,9621.0,7759.0,10730.0
EL DORADO,3391.0,7826.0,7754.0,5825.0,6374.0,7358.0
FRESNO,1052242.0,1330061.0,1143604.0,1153016.0,1168603.0,1063650.0
GLENN,176757.0,255438.0,235938.0,323877.0,274496.0,306666.0
HUMBOLDT,13227.0,9708.0,8064.0,6919.0,17963.0,14344.0
IMPERIAL,300653.0,479427.0,501162.0,549288.0,529226.0,1085611.0
INYO,2651.0,6158.0,4017.0,6178.0,2960.0,13083.0
KERN,863697.0,1036424.0,1074939.0,1040816.0,865967.0,1105928.0
KINGS,400170.0,467652.0,381474.0,352869.0,327421.0,534172.0
LAKE,16458.0,36155.0,32784.0,33636.0,20845.0,20554.0
LASSEN,8945.0,47297.0,54440.0,45325.0,67966.0,115897.0
LOS ANGELES,9554.0,16936.0,31480.0,47801.0,10545.0,27221.0
MADERA,257514.0,513984.0,481262.0,488218.0,401422.0,479860.0
MARIN,3524.0,5935.0,3290.0,13819.0,19590.0,14568.0
MARIPOSA,388.0,1067.0,249.0,1330.0,1129.0,2350.0
MENDOCINO,24878.0,41847.0,39011.0,60313.0,60217.0,48395.0
MERCED,293035.0,643879.0,672895.0,687871.0,691080.0,736913.0
MODOC,70549.0,191629.0,187974.0,208182.0,202118.0,203265.0
MONO,6008.0,20534.0,16172.0,21032.0,14695.0,33752.0
MONTEREY,346057.0,250387.0,260581.0,289232.0,363877.0,333921.0
NAPA,46705.0,59485.0,58425.0,57182.0,121400.0,66719.0
NEVADA,629.0,3826.0,4487.0,2283.0,2821.0,1891.0
ORANGE,7786.0,7415.0,5172.0,6090.0,2696.0,4351.0
PLACER,22843.0,33499.0,22546.0,25080.0,14199.0,17703.0
PLUMAS,6839.0,18159.0,15328.0,12647.0,21409.0,18958.0
RIVERSIDE,204715.0,232528.0,199725.0,177518.0,208993.0,295813.0
SACRAMENTO,79588.0,115706.0,128814.0,89385.0,131135.0,157663.0
SAN BENITO,28285.0,36046.0,40345.0,19083.0,25332.0,34637.0
SAN BERNARDINO,21466.0,38587.0,42388.0,33364.0,36151.0,23130.0
SAN DIEGO,79164.0,102420.0,78284.0,69165.0,63142.0,45371.0
SAN JOAQUIN,406582.0,694524.0,557445.0,658114.0,793525.0,814239.0
SAN LUIS OBISPO,85326.0,97357.0,129905.0,152231.0,123241.0,144887.0
SAN MATEO,3754.0,5883.0,3655.0,2228.0,4149.0,2479.0
SANTA BARBARA,105931.0,128044.0,123087.0,110801.0,147277.0,161792.0
SANTA CLARA,15176.0,27271.0,20781.0,26982.0,22627.0,20069.0
SANTA CRUZ,23886.0,28511.0,17168.0,20501.0,19551.0,14296.0
SHASTA,4344.0,27941.0,23490.0,27965.0,38451.0,39322.0
SIERRA,960.0,3660.0,3288.0,3604.0,4628.0,6367.0
SISKIYOU,36430.0,127122.0,102882.0,219943.0,147700.0,198347.0
SOLANO,82050.0,112329.0,115692.0,124031.0,174137.0,189065.0
SONOMA,63549.0,95921.0,160816.0,147060.0,85984.0,157249.0
STANISLAUS,264584.0,549734.0,422353.0,436977.0,485101.0,577755.0
SUTTER,254037.0,273278.0,308578.0,309890.0,209025.0,186021.0
TEHAMA,49875.0,114410.0,80401.0,105458.0,96114.0,117708.0
TRINITY,233.0,1339.0,1711.0,914.0,1119.0,1446.0
TULARE,636817.0,869497.0,905252.0,807498.0,1034693.0,1186461.0
TUOLUMNE,972.0,990.0,811.0,689.0,1043.0,942.0
VENTURA,114956.0,132323.0,129365.0,107091.0,144052.0,120165.0
YOLO,269281.0,308091.0,293800.0,225166.0,264668.0,218287.0
YUBA,74726.0,116396.0,76065.0,79129.0,105853.0,119638.0